### ISSUE TITLE
Threads "JMX server connection timeout*" is increasing

### ISSUE THREAD

**Issue by dinegri** [Appdynamics/kafka-monitoring-extension#9]
Hi, 

we are using Kafka Monitoring extension in our Kafka Broker. We have observed a leak of number os thread in our broker, something roundabout 30000 thread running from JMX Metrics.

I have many threads named as "JMX server connection timeout <id>", those threads have 2 minutes of timeout, but it seems they are still transferring data once those threads never finishes

My question is: Is kafka monitoring extensions reusing connections? It is closing the connections after collecting metrics?

Is there any setup that I can do to avoid these higher number of threads in my broker in the agent side?

**Comment by ghost** [comment]
Hi, 
The latest Kafka Monitoring Extension v2.0.3 has bug fixes for connection leak, can you please confirm if you're using the latest version.

Thanks
Vishaka 

cc: @kunalgupApDx

**Comment by dinegri** [comment]
Hi, thanks for your quick response

We are using v2.0.0, we will upgrade it and check how it behaves.
